"""Qualify AT framing through a diskless guest's generic FTDI USB surrogate."""
import argparse
import hashlib
import json
import lzma
from pathlib import Path
import shlex
import subprocess

from validate_recovery_guest_ssh import run as qualify_ram
from validate_recovery_ssh import client


def run(directory, key, modules, port):
    directory = Path(directory).absolute()
    qualify_ram(key, directory, port)
    command = client(key, directory / 'known_hosts', port)
    evidence_modules = []
    for name in ('usbserial', 'ftdi_sio'):
        data = lzma.decompress((modules / (name + '.ko.xz')).read_bytes())
        command[-1] = 'cat > /run/' + name + '.ko && insmod /run/' + name + '.ko'
        result = subprocess.run(command, input=data, capture_output=True, timeout=20)
        if result.returncode:
            raise RuntimeError('Guest module load failed: ' + result.stderr.decode(errors='replace'))
        evidence_modules.append(dict(name=name, sha256=hashlib.sha256(data).hexdigest()))
    # Literal independent expected transcript, not generated by the engine under test.
    requests = 'ATE0\rAT+CMEE=1\rAT+CPIN?\rAT+CPIN="1234"\rAT+CEREG?\rAT+CFUN=4\rAT+CEREG?\rAT+BOOTLDR\r'
    expected = (b'ATE0\r\r\nOK\r\n\r\nOK\r\n\r\n+CPIN: SIM PIN\r\nOK\r\n'
                b'\r\nOK\r\n\r\n+CEREG: 0,1\r\nOK\r\n\r\nOK\r\n'
                b'\r\n+CEREG: 0,0\r\nOK\r\n\r\nERROR\r\n')
    script = ('stty -F /dev/ttyUSB0 115200 raw -echo && exec 3<>/dev/ttyUSB0; '
              'printf %s ' + shlex.quote(requests) + ' >&3; '
              'timeout 15 dd bs=1 count=' + str(len(expected)) + ' <&3 2>/dev/null')
    command[-1] = 'sh -c ' + shlex.quote(script)
    result = subprocess.run(command, capture_output=True, timeout=25)
    (directory / 'transcript.json').write_text(json.dumps(dict(returncode=result.returncode,
        stdout=result.stdout.decode(errors='replace'), stderr=result.stderr.decode(errors='replace')), indent=2)+'\n')
    if result.returncode or result.stdout != expected:
        raise RuntimeError('Guest AT transcript differs; retained transcript.json')
    evidence = dict(status='passed', modules=evidence_modules,
                    scope='Diskless guest FTDI surrogate to host AT engine, synthetic locked SIM',
                    composite_usb_qualified=False, packet_networking_qualified=False)
    (directory / 'modem-acceptance.json').write_text(json.dumps(evidence, indent=2)+'\n')
    return evidence


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--output', required=True, type=Path)
    parser.add_argument('--key', required=True, type=Path)
    parser.add_argument('--modules', required=True, type=Path)
    parser.add_argument('--port', required=True, type=int)
    args = parser.parse_args()
    print(json.dumps(run(args.output, args.key, args.modules, args.port), indent=2))
